# Generated by Django 2.2.5 on 2020-04-13 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodschannel',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodschannel',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodschannelgroup',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodschannelgroup',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='skuspecification',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skuspecification',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='spuspecification',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='spuspecification',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='GoodsVisitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='创建时间')),
                ('update_time', models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 16, 54, 47, 360391), verbose_name='更新时间')),
                ('count', models.IntegerField(default=0, verbose_name='访问量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='统计日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '统计分类商品访问量',
                'verbose_name_plural': '统计分类商品访问量',
                'db_table': 'tb_goods_visit',
            },
        ),
    ]
