# Generated by Django 2.2.5 on 2020-04-13 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200413_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsvisitcount',
            old_name='count',
            new_name='counts',
        ),
        migrations.AlterField(
            model_name='brand',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodschannel',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodschannel',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodschannelgroup',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodschannelgroup',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goodsvisitcount',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodsvisitcount',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='skuspecification',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skuspecification',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='spuspecification',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='spuspecification',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 13, 17, 26, 14, 161414), verbose_name='更新时间'),
        ),
    ]
