# Generated by Django 2.2.5 on 2020-04-09 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200408_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_time',
            field=models.TimeField(auto_now_add=datetime.datetime(2020, 4, 9, 21, 23, 23, 841611), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='address',
            name='update_time',
            field=models.TimeField(auto_now=datetime.datetime(2020, 4, 9, 21, 23, 23, 841611), verbose_name='更新时间'),
        ),
    ]
