# Generated by Django 2.2.5 on 2020-04-07 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QQUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.TimeField(auto_now_add=datetime.datetime(2020, 4, 7, 12, 15, 53, 169704), verbose_name='创建时间')),
                ('update_time', models.TimeField(auto_now=datetime.datetime(2020, 4, 7, 12, 15, 53, 169704), verbose_name='更新时间')),
                ('openid', models.CharField(db_index=True, max_length=40, verbose_name='openid')),
            ],
            options={
                'verbose_name': 'QQ登录用户数据',
                'verbose_name_plural': 'QQ登录用户数据',
                'db_table': 'tb_oauth_qq',
            },
        ),
    ]
